Repository HackYourFuture-CPH/FP-annotatetheweb-class10, pull requests merged in 2020-01, with the labels that each got.

#124 Register form component
  src/client/assets/images/signup-frame.png
  src/client/components/Header/Header.css
  src/client/components/Pages/Register/RegisterPage.component.js
  src/client/components/Pages/Register/RegisterPage.css
  src/client/components/Pages/Register/RegisterPage.story.js
  src/client/components/RegisterForm/Register.component.js
  src/client/components/RegisterForm/Register.css
  src/client/components/RegisterForm/Register.story.js
  src/client/components/registerFormLogin/registerFormLogin.component.js
  src/client/components/registerFormLogin/registerFormLogin.css
  src/client/components/registerFormLogin/registerFormLogin.story.js
  src/client/components/signup/SignupButtons/signupButtons.css
  src/client/components/signup/checkbox/signupCheckBox.component.js
  src/client/components/signup/checkbox/signupCheckBox.css
  src/client/components/signup/signupTextFields/signupTextFields.css
  src/client/components/signup/title/SignupTitle.component.js
  src/client/components/signup/title/signupTitle.css
  src/client/components/signup/title/signupTitle.story.js
  src/client/components/signup/title/signupTitle.test.js
Labels: frontend

#138 #136 Bugfix - Delete modules router
  src/server/api/routes/api-router.js
Labels: backend

#121 issue#35 endpoint update annotation #35
  package.json
  src/client/assets/images/signup-frame.png
  src/client/components/Header/Header.css
  src/client/components/Pages/Register/RegisterPage.component.js
  src/client/components/Pages/Register/RegisterPage.css
  src/client/components/Pages/Register/RegisterPage.story.js
  src/client/components/RegisterForm/Register.component.js
  src/client/components/RegisterForm/Register.css
  src/client/components/RegisterForm/Register.story.js
  src/client/components/registerFormLogin/registerFormLogin.component.js
  src/client/components/registerFormLogin/registerFormLogin.css
  src/client/components/registerFormLogin/registerFormLogin.story.js
  src/client/components/signup/SignupButtons/signupButtons.css
  src/client/components/signup/checkbox/signupCheckBox.component.js
  src/client/components/signup/checkbox/signupCheckBox.css
  src/client/components/signup/signupTextFields/signupTextFields.css
  src/client/components/signup/title/signupTitle.css
  src/client/components/signup/title/signupTitle.js
  src/client/components/signup/title/signupTitle.story.js
  src/client/components/signup/title/signupTitle.test.js
  src/server/api/controllers/annotations.controller.js
  src/server/api/routes/annotations.router.js
  src/server/api/routes/router.js
  src/server/config/swagger.json
Labels: backend

#122 #111 #112 #113 #114 Projects router, controllers, swagger
  src/server/api/controllers/projects.controller.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/projects.router.js
  src/server/api/routes/users.router.js
  src/server/config/swagger.json
Labels: backend

#132 #131 Create endpoints for Users
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
  src/server/config/swagger.json
Labels: backend

#119 Feature/107-110/endpoints for comments
  src/server/api/controllers/comments.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/comments.router.js
  src/server/config/swagger.json
  src/server/migrations/20191227195759_comments.js
  src/server/seeds/005_00_annotations.js
  src/server/seeds/006_00_comments.js
Labels: backend

#127 endpoint to delete annotation
  src/client/firebase/configure.js
  src/server/api/controllers/annotations.controller.js
  src/server/api/routes/annotations.router.js
  src/server/config/swagger.json
Labels: backend

#129 #128 Bugfix - Get annotation by id
  src/server/api/controllers/annotations.controller.js
  src/server/api/routes/annotations.router.js
  src/server/api/routes/api-router.js
Labels: backend

#145 #144 Footer fix
  src/client/components/Footer/Footer.css
Labels: bug, frontend

#147 #146 Fixed content-text
  src/client/components/content/Content.css
Labels: bug, frontend

#154 removes define plugin
  webpack.config.js
Labels: backend, frontend

#157 Bugfix Swagger
  src/server/api/routes/annotations.router.js
  src/server/config/swagger.json
Labels: backend, bug

#139 #133 Responsive view of login page
  src/client/components/FormLoginRegister/FormLoginRegister.component.js
  src/client/components/FormLoginRegister/FormLoginRegister.css
  src/client/components/FormLoginRegister/FormLoginRegister.story.js
  src/client/components/FormloginRegister/FormLoginRegister.css
  src/client/components/LoginPage/FormLogin/FormLogin.component.js
  src/client/components/LoginPage/FormLogin/FormLogin.css
  src/client/components/LoginPage/FormLogin/FormLogin.story.js
  src/client/components/LoginPage/LoginPage.component.js
  src/client/components/LoginPage/LoginPage.css
Labels: frontend

#162 Bug/135/edit login page component
  src/client/components/FormButton/FormButton.component.js
  src/client/components/FormButton/FormButton.story.js
  src/client/components/FormLogin/FormLogin.component.js
  src/client/components/FormLogin/FormLogin.css
  src/client/components/FormLogin/FormLogin.story.js
  src/client/components/LoginPage/FormButton/FormButton.component.js
  src/client/components/LoginPage/FormButton/FormButton.css
  src/client/components/LoginPage/FormButton/FormButton.story.js
  src/client/components/LoginPage/FormButton/FormButton.test.js
  src/client/components/LoginPage/FormField/FormField.component.js
  src/client/components/LoginPage/FormField/FormField.css
  src/client/components/LoginPage/FormField/FormField.story.js
  src/client/components/LoginPage/FormField/FormField.test.js
  src/client/components/LoginPage/FormLine/FormLine.component.js
  src/client/components/LoginPage/FormLine/FormLine.css
  src/client/components/LoginPage/FormLine/FormLine.story.js
  src/client/components/LoginPage/FormLine/FormLine.test.js
  src/client/components/LoginPage/FormLoginRegister/FormLogin.story.js
  src/client/components/LoginPage/FormLoginRegister/FormLoginRegister.component.js
  src/client/components/LoginPage/FormLoginRegister/FormLoginRegister.css
  src/client/components/LoginPage/FormTitle/FormTitle.component.js
  src/client/components/LoginPage/FormTitle/FormTitle.css
  src/client/components/LoginPage/FormTitle/FormTitle.story.js
  src/client/components/LoginPage/FormTitle/FormTitle.test.js
  src/client/components/LoginPage/LoginPage.component.js
  src/client/components/signup/SignupButtons/SignupButtons.component.js
Labels: bug, frontend

#161 Feature#160 moved folder Pages
  src/client/App.js
  src/client/pages/Home/HomePage.js
  src/client/pages/Login/LoginPage.js
  src/client/pages/Projects/ProjectsPage.js
  src/client/pages/Register/RegisterPage.js
  src/client/pages/Screenshots/ScreenshotsPage.js
  src/client/pages/User/UserPage.js
Labels: frontend

#173 Functioning homepage
  src/client/App.js
  src/client/assets/images/HomePageImage.png
  src/client/assets/images/HomePageImageMobile.png
  src/client/assets/images/imageLogin.png
  src/client/assets/images/left-background.png
  src/client/components/FormLoginRegister/FormLoginRegister.component.js
  src/client/components/FormLoginRegister/FormLoginRegister.css
  src/client/components/FormLoginRegister/FormLoginRegister.story.js
  src/client/components/Header/Header.css
  src/client/components/MobileMenu/MobileMenu.component.js
  src/client/components/MobileMenu/MobileMenu.css
  src/client/components/NavBar/NavBar.component.js
  src/client/components/NavBar/NavBar.css
  src/client/components/NavBar/NavBar.story.js
  src/client/components/RegisterButton/RegisterButton.component.js
  src/client/components/RegisterButton/RegisterButton.css
  src/client/components/RegisterButton/RegisterButton.test.js
  src/client/components/ToggleButton/ToggleButton.css
  src/client/components/UrlInput/UrlInput.css
  src/client/context/AuthContext.js
  src/client/pages/Home/HomePage.css
  src/client/pages/Home/HomePage.js
  src/server/seeds/002_00_users.js
Labels: frontend

#165 Feature/75/annotation story
  package.json
  src/client/components/Annotation/Annotation.css
  src/client/components/Annotation/AnnotationWrapper.jsx
  src/client/components/Annotation/CustomAnnotation.component.js
  src/client/components/Annotation/CustomAnnotation.story.js
  src/client/components/Annotation/EditorWrapper.js
  src/client/pages/Home/HomePage.js
  src/server/api/controllers/annotations.controller.js
  src/server/api/controllers/comments.controller.js
  src/server/api/controllers/projects.controller.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/annotations.router.js
  src/server/config/swagger.json
Labels: frontend

#181 Feature/164/create register page
  src/client/components/FormButton/FormButton.css
  src/client/components/FormField/FormField.component.js
  src/client/components/FormField/FormField.css
  src/client/components/FormLoginRegister/FormLoginRegister.component.js
  src/client/components/FormSignUp/FormSignUp.component.js
  src/client/components/FormSignUp/FormSignUp.css
  src/client/components/FormTitle/FormTitle.component.js
  src/client/components/FormTitle/FormTitle.css
  src/client/components/FormTitle/FormTitle.test.js
  src/client/components/Header/Header.css
  src/client/firebase/auth.js
  src/client/index.css
  src/client/pages/Register/Register.css
  src/client/pages/Register/RegisterPage.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
  src/server/migrations/20200119150723_adding_user_name_to_users.js
  src/server/seeds/002_00_users.js
  webpack.config.js
Labels: frontend

#187 #174 Redirect user to projects page
  src/client/pages/Home/HomePage.js
Labels: frontend

#180 issue #134 new project page
  src/client/components/Annotation/Annotation.css
  src/client/components/Annotation/AnnotationWrapper.jsx
  src/client/components/Annotation/CustomAnnotation.component.js
  src/client/components/Button/Button.component.jsx
  src/client/components/Header/Header.css
  src/client/components/ListOfBlogCard/ListOfBlogCard.component.jsx
  src/client/components/Loading/Loading.component.jsx
  src/client/components/Loading/Loading.css
  src/client/components/MenuButton/MenuButton.component.jsx
  src/client/components/MenuButton/MenuButton.css
  src/client/components/MenuButton/MenuButton.story.js
  src/client/components/MessageParagraph/MessageParagraph.component.jsx
  src/client/components/ProfileSummary/ProfileSummary.component.js
  src/client/components/ProfileSummary/ProfileSummary.css
  src/client/components/ProjectPage.story.js
  src/client/components/RegisterButton/RegisterButton.css
  src/client/container/BlogCardList/BlogCardList.component.jsx
  src/client/container/CommentBox/BlogCard.component.jsx
  src/client/container/CommentBox/BlogCardcss.css
  src/client/container/DropDown/DropDown.component.jsx
  src/client/pages/Home/HomePage.js
  src/client/pages/Projects/ProjectsPage.css
  src/client/pages/Projects/ProjectsPage.js
Labels: frontend

#189 Error page 404
  src/client/App.js
  src/client/assets/images/ErrorImage.jpg
  src/client/components/ErrorComponent/Error.component.js
  src/client/components/ErrorComponent/Error.css
  src/client/components/ErrorComponent/Error.story.js
  src/client/components/ErrorPage/ErrorPage.component.js
  src/client/components/ErrorPage/ErrorPage.css
  src/client/components/ErrorPage/ErrorPage.story.js
  src/client/pages/ErrorPage/ErrorPage.css
  src/client/pages/ErrorPage/ErrorPage.js
Labels: frontend

#192 #169 LoginPage, RegisterPage, Home saves/uses user_id, screenshot_key to/from local storage
  src/client/context/AuthContext.js
  src/client/pages/Home/HomePage.js
  src/client/pages/Login/LoginPage.css
  src/client/pages/Login/LoginPage.js
  src/client/pages/Register/RegisterPage.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
  src/server/config/swagger.json
  src/server/migrations/20200126132218_add_email_column.js
  src/server/seeds/002_00_users.js
Labels: backend, frontend

#190 Feature/184/home page mobile
  src/client/assets/images/codeart-logo2.png
  src/client/assets/images/hyf-logo2.png
  src/client/components/ErrorComponent/Error.css
  src/client/components/ErrorPage/ErrorPage.css
  src/client/components/Footer/Footer.css
  src/client/components/Header/Header.css
  src/client/components/MobileMenu/MobileMenu.component.js
  src/client/components/MobileMenu/MobileMenu.css
  src/client/components/RegisterButton/RegisterButton.css
  src/client/components/ToggleButton/ToggleButton.css
  src/client/components/UrlInput/UrlInput.component.jsx
  src/client/components/content/Content.component.js
  src/client/components/content/Content.css
  src/client/pages/ErrorPage/ErrorPage.css
  src/client/pages/Home/HomePage.css
  src/client/pages/Home/HomePage.js
  src/client/pages/Projects/ProjectsPage.css
  src/client/pages/Projects/ProjectsPage.js
Labels: frontend
